title: gndclouds
email: gndclouds@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Heya, I build web projects as part of tiny factories while thinking about strategies for climate mitigation. Some areas I have been thinking about are Biomimetic Manufacturing, People Computer Co-creation, and Infrastructure Resiliency.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gndclouds.cc"
twitter_username: gndclouds
github_username:  gndclouds
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: content


collections:
  topics:
    output: true
    permalink: /:name/
  notes:
    output: true
    permalink: /:name/
  books:
    output: true
    permalink: /books/:name/
  projects:
    output: true
    permalink: /:name/
  clips:
    output: true
    permalink: /:name/
